### ISSUE TITLE
Offset in aligned curves

### ISSUE THREAD

**Issue by glegarda** [jamesmatuk/EFDA-of-Persistence-Landscapes#3]
Hi James,

I was trying your implementation on some data, and I noticed something rather unexpected. When I compute the mean aligned landscape from the corresponding SRVF representation that I get from `align_landscapes`, an offset appears on the right hand side. For example, I tried a simple case with two 2D landscapes, computed from the following diagrams:
```
diagram_1 = [[0.083, 0.708], [0.344, 0.448]]
diagram_2 = [[0.292, 0.917], [0.396, 0.500]]
```
This results in the following two landscapes:

![landscapes](https://github.com/user-attachments/assets/a3654d97-520f-4eca-8f62-c3279667b86b)

After aligning them, I take the mean SRVF representation and transform it back into a landscape with the `q_to_curve` function, but this is what I get:

![aligned_offset](https://github.com/user-attachments/assets/dfb2b13b-d76e-429f-9f5c-cefc15b62096)

As you can see, the first landscape dips below the zero line. While this is not particularly noticeable in this case, I have come across much more severe situations, where the landscapes flatten way above the zero line. I checked both `q_to_curve` and `curve_to_q` functions to see if anything could be going on there, but they do not seem to be the issue. I tried increasing the maximum number of iterations and reducing the minimum error in `align_landscapes`, but that did not have any effect either.

Any idea as to what might be happening?

**Comment by jamesmatuk** [comment]
Hi Guillermo,

Did you use the ProjectC function when transforming the mean SRVF back to
the data space, as in: q_to_curve(ProjectC(muQ))?

I think that we saw this issue in the past as well, in particular when we
were trying to treat landscapes as 'open' curves. The ProjectC function
forces the SRVF to correspond to a closed curve, i.e. the value at 0 and
the value at 1 have to be the same (Ideally this will be 0). If this
doesn't resolve your issue, I can think of other ways to resolve and share.

Best,
James

**Comment by glegarda** [comment]
Brilliant! That worked as expected, thanks! I don't know if you want to close the issue or leave it open in case someone else happens to have the same problem. I'll leave this up to you :)

Cheers,
Guillermo
